#:schema node_modules/wrangler/config-schema.json
name = "better-rammerhead"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
# Replace example.com with your domain name hosting a Rammerhead Browser proxy
# Example: rhbrowser.example.com and secretbrowser.example.com would work with these:
# routes = [
#   { pattern = "*.example.com/static/css/main*", zone_name = "example.com" }
# 	{ pattern = "*.example.com/static/js/main*", zone_name = "example.com" }
# ]

[observability]
enabled = true

[placement]
mode = "smart"
